import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig, loadEnv } from 'vite';
import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

/**
 * Load .env.keys file (generated by `npm run setup`) and merge into env.
 * This allows API keys configured via the setup wizard to be available
 * as VITE_KEY_* environment variables at build/dev time.
 */
function loadKeysFile(root: string): Record<string, string> {
	const keysFile = resolve(root, '.env.keys');
	if (!existsSync(keysFile)) return {};

	const lines = readFileSync(keysFile, 'utf8').split('\n');
	const env: Record<string, string> = {};

	for (const line of lines) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith('#')) continue;
		const eq = trimmed.indexOf('=');
		if (eq === -1) continue;
		const key = trimmed.slice(0, eq).trim();
		const val = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
		if (key.startsWith('VITE_')) env[key] = val;
	}

	return env;
}

export default defineConfig(({ root = process.cwd() }) => {
	const keysEnv = loadKeysFile(root);

	return {
		plugins: [sveltekit()],
		define: {
			// Inject .env.keys values as compile-time constants
			...Object.fromEntries(
				Object.entries(keysEnv).map(([k, v]) => [`import.meta.env.${k}`, JSON.stringify(v)])
			),
		},
		// @ts-expect-error — vitest adds 'test' to the config
		test: {
			globals: true,
			environment: 'jsdom',
		},
	};
});
